/*
 *  languages.h
 *      header file fore defining the different languages that can be used.
 *      designed to be easily modifiable so languages can be added easily.
 */

#ifndef _LANGUAGES_H_
#define _LANGUAGES_H_

#define MAX_EXTS 3

typedef struct _lang_t
{
    /* the name of the programming language */
    char *name;
    /* an array of file extensions for the language */
    char *ext[MAX_EXTS];
    /* string indicating the start of a block comment */
    char *startblk;
    /* string indicating the end of a block comment */
    char *endblk;
    /* string indicating an end-of-line comment */
    char *eol;
} lang_t;

#define NUM_LANGS 27

lang_t langs[NUM_LANGS] =
{
    {"C",
        {".c", ".h",},
        "/*",
        "*/",
        "//",
    },
    {"C++",
        {".cc", ".hh",},
        "/*",
        "*/",
        "//"
    },
    {"Make",
        {"Makefile",},
        NULL,
        NULL,
        "#",
    },
    {"Java",
        {".java",},
        "/*",
        "*/",
        "//",
    },
    {"SQL",
        {".sql",},
        "/*",
        "*/",
        "--",
    },
    {"Haskell",
        {".hs", ".lhs",},
        "{-",
        "-}",
        "--",
    },
    {"Perl",
        {".pl", ".pm",},
        NULL,
        NULL,
        "%",
    },
    {"PHP",
        {".php",},
        "/*",
        "*/",
        "//",
    },
    {"Shell",
        {".sh", ".bash",},
        NULL,
        NULL,
        "#",
    },
    {"R",
        {".r", ".R",},
        NULL,
        NULL,
        "#",
    },
    {"MATLAB",
        {".m",},
        "%{",
        "%}",
        "%",
    },
    {"Python",
        {".py",},
        "\"\"\"",
        "\"\"\"",
        "#",
    },
    {"Assembly",
        {".asm", ".s",},
        NULL,
        NULL,
        ";",
    },
    {"Lisp",
        {".lsp", ".lisp",},
        NULL,
        NULL,
        ";",
    },
    {"Scheme",
        {".scm",},
        NULL,
        NULL,
        ";",
    },
    {"Markdown",
        {".md",},
        NULL,
        NULL,
        NULL,
    },
    {"HTML",
        {".htm", ".html",},
        "<!--",
        "-->",
        NULL,
    },
    {"Erlang",
        {".erl", ".hrl",},
        NULL,
        NULL,
        "%",
    },
    {"Forth",
        {".4th", ".fs",},
        "( ",
        ")",
        "\\ ",
    },
    {"Lua",
        {".lua",},
        "--[[",
        "]]",
        "--",
    },
    {"Tcl",
        {".tcl",},
        NULL,
        NULL,
        "#",
    },
    {"Smalltalk",
        {".sm", ".st",},
        "\"",
        "\"",
        NULL,
    },
    {"Fortran",
        {".f77", ".f95",},
        NULL,
        NULL,
        "!",
    },
    {"Julia",
        {".jl",},
        NULL,
        NULL,
        "#",
    },
    {"VHDL",
        {".vhdl",},
        NULL,
        NULL,
        "--",
    },
    {"LaTeX",
        {".tex",},
        NULL,
        NULL,
        "%",
    },
    {"Lout",
        {".lout",},
        NULL,
        NULL,
        "#",
    },
};

#endif /* _LANGUAGES_H_ */
