.\" Process this file with
.\" groff -man -Tascii sloc.1
.\"
.TH SLOC 1 "sloc-1.1" "" "General Commands Manual"
.SH NAME
sloc \- simple source-lines-of-code counter
.SH SYNOPSIS
.B sloc
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-n ]
.RB [ \-t
.BR lang ]
.RB [ \- ]
.RB [ file ]
.RB [ ... ]
.SH DESCRIPTION
.B sloc
is a simple program that counts the total number of lines of code in source
files. It can count lines of code in the specified file(s), or in the current
directory. This program currently understands 40 languages, and can be
easily extended by adding languages to the
.I languages.h
header file.
.SH ARGUMENTS
.TP
.B \-v
Print version information about the program and exit without counting the
lines of code.
.TP
.B \-h
Print usage information about the program, then exit.
.TP
.B \-n
When printing the number of lines of code, do not print the totals.
.TP
.B \-t lang
Read code from stdin, using the given tag as the language name. If the
language name is not recognized, print an error message.
.TP
.B \-
Read the list of filenames to count from standard input, one per line.
.SH AUTHOR
Copyright (c) 2013-14 Brian Kubisiak <velentr.rc@gmail.com>
